// shared variables
var nbBlock = 0;


// variables for the part to run
const AUDIO_KEY_AG = '../stimuli/600_160ms.mp3';

var id = 123456789;
var myTrial = new TrialAG(id);


var nbBlockRelative_ag = 0;

const RANDOM_ICH_AG = Math.random();
const RANDOM_SIM_AG = Math.random();


const INSTRUCTION_TEXT_AG = {
    english: `Please place your LEFT AND RIGHT INDEX FINGER on the 'S'-KEY and 'L'-KEY and your THUMBS on 'SPACE'.
    <br>
    In this experiment, it is your task to generate a tone by pressing a key and to then evaluate the tone.
    <br>
    At the beginning of each trial you will be presented with a '+'. As soon as the '+' has disappeared, you can respond.
    <br>
    <strong>Press 'SPACE' at any time you choose. This will generate a sound.</strong>
    <br>
    Please pay close attention to this tone. In every trial, you will have to answer a question about this tone.
    <br>
    In ME-COMPUTER blocks, either you or the computer may have generated the sound based on your previous reactions and your current reaction. You will have to determine who produced the sound in each trial by pressing either 'S' or 'L'.
    <br>
    <strong>Example:</strong>
    <br>
    <strong>Who</strong> generated the sound?
    <br>
    <table style='width:30%; margin-left:auto; margin-right:auto'>
        <tr> <td style='width:35%; border:solid 2px'>me</td> <td style='width:30%;'></td> <td style='width:35%; border:solid 2px'>computer</td> </tr>
    </table>
    <br>
    Answer options: If you want to choose <strong>me</strong>, press 'S'.
    <br>
    If you want to choose <strong>computer</strong>, press 'L'.
    <br>
    <br>
    In the SIMULTANEOUSLY-DELAYED blocks, the sound is always generated by your key press. However, it will sound either immediately when you press 'SPACE' or with a delay.  In these blocks, on each trial, you have to determine whether the tone appeared simultaneously with your key press or with a delay.<br>
    <strong>Example:</strong>
    <br>
    <strong>When</strong> did the sound appear in relation to your key press?
    <br>
    <table style='width:30%; margin-left:auto; margin-right:auto'>
        <tr> <td style='width:35%; border:solid 2px'>simultaneous</td> <td style='width:30%;'></td> <td style='width:35%; border:solid 2px'>delayed</td> </tr>
    </table><br>
    Answer options: If you want to choose <strong>simultaneously</strong>, press 'S'.
    <br>
    If you want to choose<strong> delayed</strong>, press 'L'.
    <br>
    <br>
    <strong> Notice</strong> that you SELECT YOUR ANSWER by pressing the 'S' or the 'L' KEY. The answer options are displayed on the right / left in each trial and do not change their position. 
    <br>
    Before each block you will be informed which type of block will follow.
    <br>
    <br>
    Press 'SPACE' to continue<br>`
};

const BOX_SIMULTANEOUSLY = {
    simultaneously: `<table style='margin-left:auto; margin-right:auto'>
    <tr>
    <td style='width:150px; border:solid 2px'>simultaneous</td>
    <td style='width:100px;'></td>
    <td style='width:150px; border:solid 2px'>delayed</td>
    </tr>
    </table><br>`,
    delayed: `<table style=' margin-left:auto; margin-right:auto'>
    <tr>
    <td style='width:150px; border:solid 2px'>delayed</td>
    <td style='width:100px;'></td>
    <td style='width:150px%; border:solid 2px'>simultaneous</td>
    </tr>
    </table><br>`
};

const BOX_ICH = {
    ich: `<table style=' margin-left:auto; margin-right:auto'>
    <tr> <td style='width:120px; border:solid 2px'>me</td> <td style='width:100px;'></td> <td style='width:120px; border:solid 2px'>computer</td> </tr>
    </table><br>`,
    computer: `<table style=' margin-left:auto; margin-right:auto'>
    <tr> <td style='width:120px; border:solid 2px'>computer</td> <td style='width:100px;'></td> <td style='width:120px; border:solid 2px'>me</td> </tr>
    </table><br>`
};

const hideMouse = {
    type: "html-keyboard-response",
    stimulus: "",
    trial_duration: 1,
    on_start: () => {
        $('body').css('cursor', 'none');
    }
};

const showMouse = {
    type: "html-keyboard-response",
    stimulus: "",
    trial_duration: 1,
    on_start: () => {
        $('body').css('cursor', 'default');
    }
};